### ISSUE TITLE
Definitions for fields?

### ISSUE THREAD

**Issue by colechristini** [skissane/mkjail#2]
What I am I supposed to fill in for the fields? I am decent at bash, and I cannot figure it out. Especially $0 and $1

**Comment by skissane** [comment]
$0 and $1 aren't fields, they are the command line parameters.

The mkjail script only takes one parameter, which is name of the jail to create.
So if you run "mkjail foo" then it creates a directory /jail/foo for you
And in the script (per standard bash syntax) $1 is the first command line parameter
Whereas $0 is the name of the script, which is used in error messages
(So if you rename the script to something else, the error message will use its new name)
